# Site Information
site_name: Fluid Numerics RCC
site_author: Fluid Numerics
site_dir: public
site_url: ""
repo_name: GitHub/fluidnumerics/fluidnumerics-rcc
repo_url: https://github.com/fluidnumerics/fluidnumerics-rcc
edit_uri: edit/master/docs

# Directory where site content is located
docs_dir: docs

# Site navigation 
nav:
  - Home: README.md
  - Getting Started: start/README.md
  - Running Jobs: 
    - Running Jobs: jobs/README.md
    - Environment variables: jobs/env.md
    - Interactive Jobs: jobs/interactive_jobs.md
    - Batch Jobs: jobs/batch_jobs.md
    - GPU Accelerated Applications: jobs/gpu_applications.md
    - Deploy Containerized Applications: jobs/run_a_singularity_container.md
  - Available Hardware:
    - Available Hardware: hardware/README.md
  - Admin:
    - Deploy with Terraform : admin/DeployWithTerraform.md 
  - Contact Us: contact-us.md


theme: 
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
         
    - scheme: default 
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

plugins: []
