# Site Information
site_name: Fluid Numerics RCC
site_author: Fluid Numerics
site_dir: public
site_url: ""
repo_name: GitHub/fluidnumerics/fluidnumerics-rcc
repo_url: https://github.com/fluidnumerics/fluidnumerics-rcc
edit_uri: edit/master/docs

# Directory where site content is located
docs_dir: docs

# Site navigation 
nav:
  - Home: README.md
  - Ogopogo:
    - Getting Started:
      - Getting Started: ogopogo/start/README.md
      - Porting Guide: ogopogo/start/porting-best-practices.md
    - Running Jobs: 
      - Running Jobs: ogopogo/jobs/README.md
      - Interactive Jobs: ogopogo/jobs/interactive_jobs.md
      - Batch Jobs: ogopogo/jobs/batch_jobs.md
      - Environment variables: ogopogo/jobs/env.md
      - GPU Accelerated Applications: ogopogo/jobs/gpu_applications.md
      - Deploy Containerized Applications: ogopogo/jobs/run_a_singularity_container.md
      - Check Job Status: ogopogo/jobs/job_history.md 
    - Software:
      - Ogopogo: software/Ogopogo.md
    - Hardware:
      - Infrastructure Overview: ogopogo/hardware/README.md
      - Ogopogo: ogopogo/hardware/Ogopogo.md
  - For Admins:
    - Working with Terraform: admin/Terraform.md
    - Codelabs:
      - Deploy and Test Fluid Numerics Research Computing Cloud: codelabs/deploy-test-rcc/index.html
  - Contact Support: contact-us.md


theme: 
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
         
    - scheme: default 
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins: []
