steps:


- id: Build Image
  name: 'hashicorp/packer:latest'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","subnet=${_SUBNETWORK}",
        "-var","image_name=${_IMAGE_FAMILY}-${SHORT_SHA}",
        "-var","image_family=${_IMAGE_FAMILY}",
        "-var","install_root=${_INSTALL_ROOT}",
        "-var","slurm_root=${_SLURM_ROOT}",
        "-var","compiler=${_COMPILER}",
        'img/packer.json']
  waitFor: ["-"]

- id: Make Image availabe to Midjourney RCC Service Account
  name: 'gcr.io/cloud-builders/gcloud'
  args: ["compute",
         "images",
         "add-iam-policy-binding",
         "${_IMAGE_FAMILY}-${SHORT_SHA}",
         "--project=${PROJECT_ID}",
         "--member=rcc-controller-84d6euxs@midjourney-tpu.iam.gserviceaccount.com",
         "--role=roles/compute.imageUser"]

substitutions:
    _ZONE: 'us-central1-c'
    _SUBNETWORK: 'default'
    _IMAGE_FAMILY: 'midjourney-rcc'
    _INSTALL_ROOT: '/app'
    _SLURM_ROOT: '/usr/local'
    _COMPILER: 'gcc@9.4.0'

timeout : 86400s
