steps:


- id: Build Image
  name: 'hashicorp/packer:latest'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","subnet=${_SUBNETWORK}",
        "-var","image_name=${_IMAGE_FAMILY}-${SHORT_SHA}",
        "-var","image_family=${_IMAGE_FAMILY}",
        "-var","install_root=${_INSTALL_ROOT}",
        "-var","slurm_root=${_SLURM_ROOT}",
        "-var","compiler=${_COMPILER}",
        'img/packer.json']
  waitFor: ["-"]

- id: Fluid Run
  name: 'gcr.io/research-computing-cloud/rcc-run:slurm-gcp'
  args:
    - '--build-id=${BUILD_ID}'
    - '--git-sha=${COMMIT_SHA}'
    - '--project=${PROJECT_ID}'
    - '--zone=${_ZONE}'
    - '--artifact-type=gce-vm-image'
    - '--ci-file=frun.yaml'
    - '--gce-image=projects/${PROJECT_ID}/global/images/${_IMAGE_FAMILY}-${SHORT_SHA}'
    - '--rcc-tfvars=ci/rcc.auto.tfvars'


substitutions:
    _ZONE: 'us-central1-c'
    _SUBNETWORK: 'default'
    _IMAGE_FAMILY: 'midjourney-rcc-dev'
    _INSTALL_ROOT: '/app'
    _SLURM_ROOT: '/usr/local'
    _COMPILER: 'gcc@9.4.0'

timeout : 86400s
