steps:


- id: Build Image
  name: 'hashicorp/packer:latest'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","subnet=${_SUBNETWORK}",
        "-var","image_name=${_IMAGE_FAMILY}-${SHORT_SHA}",
        "-var","image_family=${_IMAGE_FAMILY}",
        'img/packer.json']
  waitFor: ["-"]

substitutions:
    _ZONE: 'us-central1-c'
    _SUBNETWORK: 'default'
    _IMAGE_FAMILY: 'fluidnumerics-rcc-dev'

timeout : 86400s
