
- name: RCC Packages
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install yum packages
      ansible.builtin.script: scripts/pkgs.sh

    - name: Install ROCm
      ansible.builtin.script: scripts/rocm.sh

    - name: Install Spack, Compilers, and MPI
      ansible.builtin.script: scripts/spack.sh

    - name: Install RadioAstronomy tools
      ansible.builtin.script: scripts/radio-astronomy.sh